### ISSUE TITLE
Link to http://europeana.eu/schemas/ is broken

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#11]
the URL http://europeana.eu/schemas/ returns a forbidden error. It needs to work as it is referenced in the DEA: 

> Metadata Specifications: The most recent version of the Metadata specifications published by Europeana and available at http://europeana.eu/schemas/ on the Effective Date

this URL needs to point (or forward) to the most recent version of the EDM metadata specification

**Comment by paul2keller** [comment]
@juliafallon this is still broken. can you assign this to someone on the technical team to fix this link. as pointed out in the comments this should be directed to https://pro.europeana.eu/resources/standardization-tools/edm-documentation

**Comment by juliafallon** [comment]
I've requested this - will update when I have confirmation this has been applied.

**Comment by juliafallon** [comment]
Done.
