### ISSUE TITLE
Fix links in "retired notes" of the Europeana Rights statements 

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#2]
The links in the retired notes point to the wrong URL of the rs.org equivalent statements

**Comment by paul2keller** [comment]
also someone may want to fix this: 

![screen shot 2017-10-19 at 20 37 22](https://user-images.githubusercontent.com/5593766/31787939-7bd144cc-b50d-11e7-92f8-bab1c09a90bf.png)

**Comment by juliafallon** [comment]
On 1) it points to the available rights statement page, that is not a mistake. 2) that's odd, looking into it

**Comment by paul2keller** [comment]
@juliafallon yes instead of http://rightsstatements.org/page/InC/1.0/?language=en the link should be http://rightsstatements.org/vocab/InC/1.0/ (and then the same for all other statements)

**Comment by juliafallon** [comment]
Thanks.  Done - for all rights statements on the terms & policies page

**Comment by paul2keller** [comment]
thanks @juliafallon one last detail before we can close this issue. on https://www.europeana.eu/portal/en/rights/orphan-work-eu.html there is a closing ' missing after the name of the new rights statement.

**Comment by juliafallon** [comment]
fixed
