### ISSUE TITLE
DEA review: Digital Object definition

### ISSUE THREAD

**Issue by verwinv** [Kennisland/EuropeanaLicensingFramework#20]
This would need to be changed in the Europeana Glossary as well as in the DEA, but I would propose a slight change to the Digital Object definition. 

> A digital representation of an object that is part of Europe's cultural and/or scientific heritage. The Digital Object can also be the original object when born digital.

I would argue that, unless there are cases where Europeana is the sole safekeeper of a specific digital object, digital objects would always be a copy of an original object, rather than the original itself.

> A digital representation of an object that is part of Europe's cultural and/or scientific heritage. The Digital Object can also be **an exact copy** of the original when born digital.

**Comment by paul2keller** [comment]
so i am not quite sure if this is correct. Europeana does not store digital objects by default. we only point to the objects at the URL provided to us by the data provider. It may be the case that that copy is not the original born digital object either, but i think that is a meaningless distinction in this context.

What we are trying to say here is simply that the digital object may be a digital representation of an analogue object or the original object itself.

**Comment by paul2keller** [comment]
i don't see how you can derive the idea that Europeana could be transformed into a long term preservation repository from the text of the DEA. The principle that Europeana will not store digital objects remains unchanged even with the changes we are proposing to make. In the light of this i really do not see a need to change this definition.

where to you get the idea that Europeana would store digital objects from?
