### ISSUE TITLE
Reinstate RR-R statement

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#3]
The RR-R statement on https://www.europeana.eu/portal/en/rights/rr-r.html is currently not available

**Comment by juliafallon** [comment]
This is now working for me - with no intervention from me - can you please check it works from your side? I'll report the bug.

**Comment by juliafallon** [comment]
Ok.  I needed to clear my cache.  The page should be published now.  Can you check please?

**Comment by paul2keller** [comment]
yes fixed now for me as well. thanks @juliafallon
