### ISSUE TITLE
Canonical link to Metadata usage guidelines is broken. 

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#5]
The canonical link to the Metadata usage guidelines is currently broken: http://www.europeana.eu/portal/data-usage-guide.html produces a 404 (the guidelines is available at https://www.europeana.eu/portal/en/rights/metadata.html) The canonical link is references in the DEA and needs to be re-instated

**Comment by juliafallon** [comment]
Checking with valentine.  This was supposed to have been reinstated but it's clearly not working.

**Comment by juliafallon** [comment]
@ashmarriotteuropeana can you advise?  My understanding was that this was a link that the tech team asked to be maintained, is it on the list?  If it's not can we please add & action it?

**Comment by ashmarriotteuropeana** [comment]
@juliafallon @paul2keller Is there any reason we can't update the URL to be correct rather than trying to make redeployments on collections? If this is the case, I have created a pull request with the updated URL here: 
https://github.com/Kennisland/EuropeanaLicensingFramework/pull/10

**Comment by juliafallon** [comment]
Yes, the url has been referenced in the DEA and other licensing framework agreements and documentation.  We are not in the position (and do not want) to update the url in these each time pro changes it's structure.

**Comment by ashmarriotteuropeana** [comment]
Correction completed as per this development ticket: https://europeana.atlassian.net/browse/EC-2518

The URL now works again on live via a redirect to the correct location.
