### ISSUE TITLE
Terms for User Contributions missing article numbers

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#6]
The Terms for User Contributions at https://www.europeana.eu/portal/en/rights/contributions.html are missing the article numbering. In general the formatting of the page is a mess (in the definitions section the defined terms should be set in **bold**)

**Comment by juliafallon** [comment]
@paul2keller do you know where the original was so I can cross reference the article numbers (do you remember was each art broken down further ie Art 1.2.i etc)  

@ashmarriotteuropeana I need to reformat this page, so I could do with your help to show me some basics please.

**Comment by paul2keller** [comment]
@Julia: https://github.com/Kennisland/EuropeanaLicensingFramework/blob/master/terms-for-user-contributions.md (note that the sub list in article 7.2 is supposed to be promoted a. b. c. ... but that type of list numbering is not supported by markdown (the language of the files that we store in Github)

**Comment by juliafallon** [comment]
ok thanks.  I need some help understanding what code I need to add to do certain things (and not mess it up) and then I'll get on it (unless anyone else wants to take this on?!)

**Comment by paul2keller** [comment]
@juliafallon any progress on this? do you still need help here?

**Comment by juliafallon** [comment]
Ash has it on his to-do list, I'll remind him of that.

**Comment by juliafallon** [comment]
This page has now been updated with article numbers and reformatted.

**Comment by paul2keller** [comment]
thanks @juliafallon !
