### ISSUE TITLE
The "can is use it facet" does not unfold in Safari with google analytics blocked

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#7]
In Safari (11.0 on macOS 10.13) the can I use it filter in the left column on search results pages does not open up when google analytics I blocked via ghostery. (on the same computer it does open up in chrome although I am also blocking google analytics and all other third party trackers in Chrome)

**Comment by paul2keller** [comment]
just to clarify, the facet does open when I unblock google analytics (and all other trackers)

**Comment by juliafallon** [comment]
@ashmarriotteuropeana can you advise how we can respond to this?

**Comment by paul2keller** [comment]
i cannot reproduce this anymore, assuming it has been fixed in the meanwhile
